server:
  port: 8086

spring:
    application:
        name: wallet-microservice
    data:
        mongodb:
            database: wallet
            uri: mongodb://jonavcar-mongodb:S5hakDNQSeKOE6JFcL4cdO6MXIPf5j9gvX6pgGhYjHX85bH5ujqpDuyQQNU9RA8FyTvJd5nSAmoiXY9iQn9etg==@jonavcar-mongodb.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@jonavcar-mongodb@
