server:
  port: 8086

spring:
    application:
        name: wallet-microservice
    data:
        mongodb:
            database: wallet
            host: localhost1
            port: 27017
            